services:
  backend:
    build: ./backend
    container_name: hackverse-backend
    hostname: hackverse
    ports:
      - "8081:8080"    # host:container (use 8081 externally, backend runs on 8080 inside)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=development
    networks:
      - hackverse-net
